# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.srcs/sources_1/ip/fifo_memory/fifo_memory.xci
# IP: The module: 'fifo_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.gen/sources_1/ip/fifo_memory/fifo_memory.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.gen/sources_1/ip/fifo_memory/fifo_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.srcs/sources_1/ip/fifo_memory/fifo_memory.xci
# IP: The module: 'fifo_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.gen/sources_1/ip/fifo_memory/fifo_memory.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/szkep/source/repos/Vivado/core_generator_1/core_generator_1.gen/sources_1/ip/fifo_memory/fifo_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
